ADD_SERVER_STATE = {}
EDIT_SERVER_STATE = {}
ADD_GROUP_STATE = {}
ADD_GROUP_SSL_STATE = {}

SCRIPT_RUN_STATE = {}
SCRIPT_CONFIRM_STATE = {}
PENDING_SERVER_CHANGES = {}
SSL_SETUP_STATE = {}
KEY_CREATE_STATE = {}
KEY_RENAME_STATE = {}
KEY_REPLACE_STATE = {}
KEY_PASTE_NEW_STATE = {}

SERVICE_INSTALL_STATE = {}
SVC_PROFILE_ADD_STATE = {}